import { v4 as uuid } from 'uuid'
import * as bcrypt from 'bcryptjs'

// ── Seeded IDs (proper UUIDs for PostgreSQL) ──────────────────────────────────
export const SEED_IDS = {
    // Users
    adminUser: 'a0000000-0000-4000-8000-000000000001',
    librarianUser: 'a0000000-0000-4000-8000-000000000002',
    readerUser: 'a0000000-0000-4000-8000-000000000003',
    readerUser2: 'a0000000-0000-4000-8000-000000000004',

    // Library cards
    card1: 'b0000000-0000-4000-8000-000000000001',

    // Categories
    catNovel: 1,
    catSkills: 2,
    catHistory: 3,
    catTech: 4,
    catPsych: 5,

    // Books
    book1: 'c0000000-0000-4000-8000-000000000001',
    book2: 'c0000000-0000-4000-8000-000000000002',
    book3: 'c0000000-0000-4000-8000-000000000003',
    book4: 'c0000000-0000-4000-8000-000000000004',
    book5: 'c0000000-0000-4000-8000-000000000005',
    book6: 'c0000000-0000-4000-8000-000000000006',
    book7: 'c0000000-0000-4000-8000-000000000007',
    book8: 'c0000000-0000-4000-8000-000000000008',
    book9:  'c0000000-0000-4000-8000-000000000009',
    book10: 'c0000000-0000-4000-8000-000000000010',
    book11: 'c0000000-0000-4000-8000-000000000011',
    book12: 'c0000000-0000-4000-8000-000000000012',
    book13: 'c0000000-0000-4000-8000-000000000013',
    book14: 'c0000000-0000-4000-8000-000000000014',
    book15: 'c0000000-0000-4000-8000-000000000015',
    book16: 'c0000000-0000-4000-8000-000000000016',
    book17: 'c0000000-0000-4000-8000-000000000017',
    book18: 'c0000000-0000-4000-8000-000000000018',
    book19: 'c0000000-0000-4000-8000-000000000019',
    book20: 'c0000000-0000-4000-8000-000000000020',
    book21: 'c0000000-0000-4000-8000-000000000021',
    book22: 'c0000000-0000-4000-8000-000000000022',
    book23: 'c0000000-0000-4000-8000-000000000023',
    book24: 'c0000000-0000-4000-8000-000000000024',
    book25: 'c0000000-0000-4000-8000-000000000025',
    book26: 'c0000000-0000-4000-8000-000000000026',
    book27: 'c0000000-0000-4000-8000-000000000027',
    book28: 'c0000000-0000-4000-8000-000000000028',

    // Borrow records
    borrow1: 'd0000000-0000-4000-8000-000000000001',
    borrow2: 'd0000000-0000-4000-8000-000000000002',
    borrow3: 'd0000000-0000-4000-8000-000000000003',
}

// ── In-memory store ───────────────────────────────────────────────────────────
export class MockDB {
    users: any[] = []
    libraryCards: any[] = []
    categories: any[] = []
    books: any[] = []
    bookCopies: any[] = []
    borrowRecords: any[] = []
    reservations: any[] = []
    fines: any[] = []

    constructor() { this.seed() }

    private async seed() {
        const hash = await bcrypt.hash('password123', 10)

        // ── Users ─────────────────────────────────────────────────────────────────
        this.users = [
            {
                id: SEED_IDS.adminUser,
                username: 'admin',
                email: 'admin@library.vn',
                passwordHash: hash,
                role: 'library_admin',
                fullName: 'Quản trị viên',
                phone: null, idCardNumber: null, dateOfBirth: null, address: null,
                isActive: true,
                lastLogin: new Date().toISOString(),
                createdAt: '2024-01-01T00:00:00Z',
            },
            {
                id: SEED_IDS.librarianUser,
                username: 'librarian',
                email: 'librarian@library.vn',
                passwordHash: hash,
                role: 'librarian',
                fullName: 'Nguyễn Thị Lan',
                phone: '0901234567', idCardNumber: null, dateOfBirth: null, address: null,
                isActive: true,
                lastLogin: new Date().toISOString(),
                createdAt: '2024-01-02T00:00:00Z',
            },
            {
                id: SEED_IDS.readerUser,
                username: 'reader',
                email: 'reader@example.com',
                passwordHash: hash,
                role: 'reader',
                fullName: 'Trần Văn Minh',
                phone: '0912345678',
                idCardNumber: '012345678901',
                dateOfBirth: '1998-05-15',
                address: '123 Đường Nguyễn Huệ, Q.1, TP.HCM',
                isActive: true,
                lastLogin: new Date().toISOString(),
                createdAt: '2024-01-10T00:00:00Z',
            },
            {
                id: SEED_IDS.readerUser2,
                username: 'reader2',
                email: 'reader2@example.com',
                passwordHash: hash,
                role: 'reader',
                fullName: 'Lê Thị Hoa',
                phone: '0923456789',
                idCardNumber: '098765432100',
                dateOfBirth: '2000-08-20',
                address: '456 Lê Lợi, Q.3, TP.HCM',
                isActive: true,
                lastLogin: null,
                createdAt: '2024-02-01T00:00:00Z',
            },
        ]

        // ── Library Cards ─────────────────────────────────────────────────────────
        this.libraryCards = [
            {
                id: SEED_IDS.card1,
                userId: SEED_IDS.readerUser,
                issuedBy: SEED_IDS.librarianUser,
                cardNumber: 'TV-2024-001',
                issuedDate: '2024-01-10',
                expiryDate: '2025-01-10',
                status: 'active',
            },
        ]

        // ── Categories ────────────────────────────────────────────────────────────
        this.categories = [
            { id: 1, name: 'Tiểu thuyết' },
            { id: 2, name: 'Kỹ năng sống' },
            { id: 3, name: 'Lịch sử' },
            { id: 4, name: 'Công nghệ' },
            { id: 5, name: 'Tâm lý học' },
            { id: 6, name: 'Khoa học' },
            { id: 7, name: 'Văn học Việt Nam' },
            { id: 8, name: 'Kinh tế - Tài chính' },
        ]

        // ── Books ─────────────────────────────────────────────────────────────────
        this.books = [
            {
                id: SEED_IDS.book1,
                isbn: '978-604-2-18901-3',
                title: 'Đắc Nhân Tâm',
                author: 'Dale Carnegie',
                publisher: 'NXB Tổng hợp TP.HCM',
                categoryId: 2,
                publishYear: 2016,
                description: 'Cuốn sách kinh điển về nghệ thuật giao tiếp và ứng xử với mọi người. Hướng dẫn cách tạo ấn tượng tốt, thuyết phục người khác và xây dựng mối quan hệ bền vững.',
                coverUrl: '/covers/dac-nhan-tam.png',
                totalCopies: 5, availableCopies: 3,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-05T00:00:00Z',
            },
            {
                id: SEED_IDS.book2,
                isbn: '978-604-1-09234-7',
                title: 'Nhà Giả Kim',
                author: 'Paulo Coelho',
                publisher: 'NXB Hội Nhà Văn',
                categoryId: 1,
                publishYear: 2020,
                description: 'Hành trình của Santiago — một cậu bé chăn cừu Tây Ban Nha đến vùng đất Ai Cập để tìm kho báu. Một câu chuyện về ước mơ và số phận.',
                coverUrl: '/covers/nha-gia-kim.png',
                totalCopies: 4, availableCopies: 0,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-05T00:00:00Z',
            },
            {
                id: SEED_IDS.book3,
                isbn: '978-604-9-72311-2',
                title: 'Tư Duy Nhanh Và Chậm',
                author: 'Daniel Kahneman',
                publisher: 'NXB Thế Giới',
                categoryId: 5,
                publishYear: 2019,
                description: 'Khám phá hai hệ thống tư duy chi phối mọi quyết định của con người: tư duy nhanh (cảm tính) và tư duy chậm (lý trí).',
                coverUrl: '/covers/tu-duy-nhanh-va-cham.png',
                totalCopies: 3, availableCopies: 2,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-06T00:00:00Z',
            },
            {
                id: SEED_IDS.book4,
                isbn: '978-604-3-45612-8',
                title: 'Sapiens: Lược Sử Loài Người',
                author: 'Yuval Noah Harari',
                publisher: 'NXB Tri Thức',
                categoryId: 3,
                publishYear: 2018,
                description: 'Hành trình tiến hóa của loài người từ thời tiền sử đến hiện đại, qua các cuộc cách mạng nhận thức, nông nghiệp và khoa học.',
                coverUrl: '/covers/sapiens.png',
                totalCopies: 6, availableCopies: 4,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-07T00:00:00Z',
            },
            {
                id: SEED_IDS.book5,
                isbn: '978-604-7-88234-1',
                title: 'Clean Code',
                author: 'Robert C. Martin',
                publisher: 'NXB Khoa học kỹ thuật',
                categoryId: 4,
                publishYear: 2021,
                description: 'Hướng dẫn viết code sạch, dễ đọc và dễ bảo trì. Các nguyên tắc và kỹ thuật giúp lập trình viên tạo ra phần mềm chất lượng cao.',
                coverUrl: null,
                totalCopies: 4, availableCopies: 4,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-08T00:00:00Z',
            },
            {
                id: SEED_IDS.book6,
                isbn: '978-604-2-33219-5',
                title: 'Atomic Habits',
                author: 'James Clear',
                publisher: 'NXB Lao Động',
                categoryId: 2,
                publishYear: 2022,
                description: 'Xây dựng thói quen tốt và loại bỏ thói quen xấu thông qua những thay đổi nhỏ nhưng đột phá. Phương pháp khoa học được chứng minh hiệu quả.',
                coverUrl: '/covers/atomic-habits.png',
                totalCopies: 5, availableCopies: 2,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-09T00:00:00Z',
            },
            {
                id: SEED_IDS.book7,
                isbn: '978-604-5-67890-3',
                title: 'Dune',
                author: 'Frank Herbert',
                publisher: 'NXB Kim Đồng',
                categoryId: 1,
                publishYear: 2023,
                description: 'Sử thi khoa học viễn tưởng vĩ đại nhất mọi thời đại. Câu chuyện về chính trị, tôn giáo và sinh thái trên hành tinh sa mạc Arrakis.',
                coverUrl: null,
                totalCopies: 2, availableCopies: 2,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-10T00:00:00Z',
            },
            {
                id: SEED_IDS.book8,
                isbn: '978-604-6-11111-0',
                title: 'Homo Deus',
                author: 'Yuval Noah Harari',
                publisher: 'NXB Tri Thức',
                categoryId: 6,
                publishYear: 2020,
                description: 'Tương lai của loài người: trí tuệ nhân tạo, bất tử và hạnh phúc. Yuval Noah Harari phác thảo lịch sử ngày mai.',
                coverUrl: null,
                totalCopies: 3, availableCopies: 1,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-11T00:00:00Z',
            },
            {
                id: SEED_IDS.book9,
                isbn: '978-604-8-12345-1',
                title: '1984',
                author: 'George Orwell',
                publisher: 'NXB Hội Nhà Văn',
                categoryId: 1,
                publishYear: 2021,
                description: 'Tiểu thuyết phản địa đàng kinh điển. Câu chuyện về một xã hội toàn trị tương lai nơi Đảng kiểm soát mọi suy nghĩ và hành động của con người.',
                coverUrl: '/covers/1984.png',
                totalCopies: 5, availableCopies: 3,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-12T00:00:00Z',
            },
            {
                id: SEED_IDS.book10,
                isbn: '978-604-8-22222-2',
                title: 'Rừng Na Uy',
                author: 'Haruki Murakami',
                publisher: 'NXB Hội Nhà Văn',
                categoryId: 1,
                publishYear: 2022,
                description: 'Câu chuyện tình yêu, mất mát và trưởng thành của chàng trai Watanabe trong bối cảnh Tokyo những năm 1960. Một tác phẩm đẹp và đau.',
                coverUrl: '/covers/rung-na-uy.png',
                totalCopies: 4, availableCopies: 2,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-13T00:00:00Z',
            },
            {
                id: SEED_IDS.book11,
                isbn: '978-604-8-33333-3',
                title: 'Harry Potter và Hòn Đá Phù Thủy',
                author: 'J.K. Rowling',
                publisher: 'NXB Trẻ',
                categoryId: 1,
                publishYear: 2023,
                description: 'Cậu bé phù thủy Harry Potter bước vào trường Hogwarts và khám phá thế giới ma thuật kỳ diệu. Bộ truyện bán chạy nhất lịch sử.',
                coverUrl: '/covers/harry-potter.png',
                totalCopies: 8, availableCopies: 5,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-14T00:00:00Z',
            },
            {
                id: SEED_IDS.book12,
                isbn: '978-604-8-44444-4',
                title: 'Cha Giàu Cha Nghèo',
                author: 'Robert T. Kiyosaki',
                publisher: 'NXB Lao Động',
                categoryId: 8,
                publishYear: 2020,
                description: 'Bài học tài chính từ hai người cha: cha ruột (nghèo) và cha nuôi (giàu). Thay đổi tư duy về tiền bạc, đầu tư và tự do tài chính.',
                coverUrl: '/covers/rich-dad-poor-dad.png',
                totalCopies: 6, availableCopies: 4,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-15T00:00:00Z',
            },
            {
                id: SEED_IDS.book13,
                isbn: '978-604-8-55555-5',
                title: 'Ikigai: Bí Quyết Sống Trường Thọ Và Hạnh Phúc',
                author: 'Héctor García & Francesc Miralles',
                publisher: 'NXB Phụ Nữ',
                categoryId: 2,
                publishYear: 2021,
                description: 'Bí quyết sống của người Nhật: tìm ra lý do tồn tại của bản thân (Ikigai) để sống lâu, khỏe mạnh và hạnh phúc.',
                coverUrl: '/covers/ikigai.png',
                totalCopies: 5, availableCopies: 3,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-01-16T00:00:00Z',
            },
            {
                id: SEED_IDS.book14,
                isbn: '978-604-8-66666-6',
                title: 'Zero to One',
                author: 'Peter Thiel',
                publisher: 'NXB Thế Giới',
                categoryId: 8,
                publishYear: 2022,
                description: 'Bí quyết xây dựng startup từ 0 lên 1. Peter Thiel - đồng sáng lập PayPal - chia sẻ tầm nhìn độc đáo về sáng tạo và kinh doanh.',
                coverUrl: '/covers/zero-to-one.png',
                totalCopies: 4, availableCopies: 4,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-01T00:00:00Z',
            },
            {
                id: SEED_IDS.book15,
                isbn: '978-604-8-77777-7',
                title: '7 Thói Quen Của Người Thành Đạt',
                author: 'Stephen R. Covey',
                publisher: 'NXB Trẻ',
                categoryId: 2,
                publishYear: 2019,
                description: 'Bảy thói quen giúp bạn trở nên hiệu quả hơn trong công việc và cuộc sống. Một trong những cuốn sách kinh doanh bán chạy nhất mọi thời đại.',
                coverUrl: null,
                totalCopies: 5, availableCopies: 2,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-02T00:00:00Z',
            },
            {
                id: SEED_IDS.book16,
                isbn: '978-604-8-88888-8',
                title: 'Tôi Tài Giỏi, Bạn Cũng Thế',
                author: 'Adam Khoo',
                publisher: 'NXB Phụ Nữ',
                categoryId: 2,
                publishYear: 2020,
                description: 'Phương pháp học tập siêu tốc của thiên tài trẻ Adam Khoo. Cách khai thác tiềm năng vô hạn của não bộ và trở thành học sinh xuất sắc.',
                coverUrl: null,
                totalCopies: 7, availableCopies: 5,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-03T00:00:00Z',
            },
            {
                id: SEED_IDS.book17,
                isbn: '978-604-8-99999-9',
                title: 'Tuổi Trẻ Đáng Giá Bao Nhiêu',
                author: 'Rosie Nguyễn',
                publisher: 'NXB Hội Nhà Văn',
                categoryId: 2,
                publishYear: 2018,
                description: 'Cuốn sách truyền cảm hứng dành cho tuổi trẻ. Những suy nghĩ về tình yêu, sự nghiệp, ước mơ và ý nghĩa của những năm tháng đẹp nhất cuộc đời.',
                coverUrl: null,
                totalCopies: 6, availableCopies: 3,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-04T00:00:00Z',
            },
            {
                id: SEED_IDS.book18,
                isbn: '978-604-9-00001-1',
                title: 'Design Patterns',
                author: 'Gang of Four (GoF)',
                publisher: 'NXB Khoa học kỹ thuật',
                categoryId: 4,
                publishYear: 2019,
                description: 'Cuốn sách kinh điển về các mẫu thiết kế phần mềm hướng đối tượng. 23 mẫu thiết kế giúp giải quyết các bài toán lập trình phổ biến.',
                coverUrl: null,
                totalCopies: 3, availableCopies: 3,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-05T00:00:00Z',
            },
            {
                id: SEED_IDS.book19,
                isbn: '978-604-9-00002-2',
                title: 'The Pragmatic Programmer',
                author: 'David Thomas & Andrew Hunt',
                publisher: 'NXB Khoa học kỹ thuật',
                categoryId: 4,
                publishYear: 2020,
                description: 'Hướng dẫn thực tế cho lập trình viên muốn trở nên chuyên nghiệp hơn. Từ triết lý lập trình đến kỹ năng mềm cần thiết trong công việc.',
                coverUrl: null,
                totalCopies: 4, availableCopies: 4,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-06T00:00:00Z',
            },
            {
                id: SEED_IDS.book20,
                isbn: '978-604-9-00003-3',
                title: 'Lược Sử Thời Gian',
                author: 'Stephen Hawking',
                publisher: 'NXB Trẻ',
                categoryId: 6,
                publishYear: 2021,
                description: 'Hành trình từ Big Bang đến Lỗ Đen. Stephen Hawking giải thích vũ trụ học theo ngôn ngữ dễ hiểu dành cho mọi độc giả.',
                coverUrl: null,
                totalCopies: 3, availableCopies: 2,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-07T00:00:00Z',
            },
            {
                id: SEED_IDS.book21,
                isbn: '978-604-9-00004-4',
                title: 'Số Đỏ',
                author: 'Vũ Trọng Phụng',
                publisher: 'NXB Văn Học',
                categoryId: 7,
                publishYear: 2018,
                description: 'Tiểu thuyết trào phúng bậc thầy của văn học Việt Nam. Câu chuyện của Xuân Tóc Đỏ — kẻ vô lại leo lên đỉnh cao xã hội thượng lưu.',
                coverUrl: null,
                totalCopies: 4, availableCopies: 4,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-08T00:00:00Z',
            },
            {
                id: SEED_IDS.book22,
                isbn: '978-604-9-00005-5',
                title: 'Tắt Đèn',
                author: 'Ngô Tất Tố',
                publisher: 'NXB Văn Học',
                categoryId: 7,
                publishYear: 2017,
                description: 'Bi kịch của người nông dân Việt Nam trước Cách mạng. Chị Dậu — hình tượng người phụ nữ khổ đau nhưng kiên cường bất khuất.',
                coverUrl: null,
                totalCopies: 3, availableCopies: 2,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-09T00:00:00Z',
            },
            {
                id: SEED_IDS.book23,
                isbn: '978-604-9-00006-6',
                title: 'Chí Phèo',
                author: 'Nam Cao',
                publisher: 'NXB Văn Học',
                categoryId: 7,
                publishYear: 2018,
                description: 'Kiệt tác văn học hiện thực Việt Nam. Bi kịch của Chí Phèo — con người bị xã hội tha hóa và khát vọng được làm người lương thiện.',
                coverUrl: null,
                totalCopies: 5, availableCopies: 5,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-10T00:00:00Z',
            },
            {
                id: SEED_IDS.book24,
                isbn: '978-604-9-00007-7',
                title: 'Đất Rừng Phương Nam',
                author: 'Đoàn Giỏi',
                publisher: 'NXB Kim Đồng',
                categoryId: 7,
                publishYear: 2019,
                description: 'Câu chuyện phiêu lưu của cậu bé An trên vùng sông nước miền Tây Nam Bộ. Bức tranh thiên nhiên hoang dã và con người Nam Bộ tươi đẹp.',
                coverUrl: null,
                totalCopies: 6, availableCopies: 4,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-11T00:00:00Z',
            },
            {
                id: SEED_IDS.book25,
                isbn: '978-604-9-00008-8',
                title: 'Ý Nghĩa Của Cuộc Sống',
                author: 'Viktor E. Frankl',
                publisher: 'NXB Tri Thức',
                categoryId: 5,
                publishYear: 2022,
                description: 'Hồi ký và lý thuyết tâm lý từ trại tập trung Auschwitz. Frankl tìm thấy ý nghĩa cuộc sống ngay trong những hoàn cảnh bi thảm nhất.',
                coverUrl: null,
                totalCopies: 4, availableCopies: 3,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-12T00:00:00Z',
            },
            {
                id: SEED_IDS.book26,
                isbn: '978-604-9-00009-9',
                title: 'Triết Học Khắc Kỷ',
                author: 'Ryan Holiday',
                publisher: 'NXB Thế Giới',
                categoryId: 5,
                publishYear: 2022,
                description: 'Áp dụng triết học Khắc Kỷ cổ đại vào cuộc sống hiện đại. Kiểm soát cảm xúc, đối mặt với khó khăn và tìm thấy sự bình thản nội tâm.',
                coverUrl: null,
                totalCopies: 3, availableCopies: 2,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-13T00:00:00Z',
            },
            {
                id: SEED_IDS.book27,
                isbn: '978-604-9-00010-0',
                title: 'Cà Phê Cùng Tony',
                author: 'Tony Buổi Sáng',
                publisher: 'NXB Trẻ',
                categoryId: 2,
                publishYear: 2020,
                description: 'Những bài viết ngắn hóm hỉnh và sâu sắc về cuộc sống, công việc và con người Việt Nam. Góc nhìn thực tế và đầy cảm hứng.',
                coverUrl: null,
                totalCopies: 6, availableCopies: 5,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-14T00:00:00Z',
            },
            {
                id: SEED_IDS.book28,
                isbn: '978-604-9-00011-1',
                title: 'Kinh Tế Học Hài Hước',
                author: 'Steven D. Levitt & Stephen J. Dubner',
                publisher: 'NXB Trẻ',
                categoryId: 8,
                publishYear: 2021,
                description: 'Khám phá ẩn sau mọi hiện tượng xã hội bằng tư duy kinh tế học. Tại sao giáo viên gian lận? Tội phạm giảm vì sao? Những câu hỏi thú vị.',
                coverUrl: null,
                totalCopies: 4, availableCopies: 3,
                createdBy: SEED_IDS.librarianUser,
                createdAt: '2024-02-15T00:00:00Z',
            },
        ]


        // ── Book Copies ───────────────────────────────────────────────────────────
        const copies: any[] = []
        this.books.forEach(book => {
            for (let i = 1; i <= book.totalCopies; i++) {
                const available = i <= book.availableCopies
                copies.push({
                    id: uuid(),
                    bookId: book.id,
                    copyCode: `${book.isbn.slice(-4)}-${String(i).padStart(3, '0')}`,
                    condition: i <= 2 ? 'good' : 'new',
                    status: available ? 'available' : 'borrowed',
                    notes: null,
                    createdAt: book.createdAt,
                })
            }
        })
        this.bookCopies = copies

        // ── Borrow Records ────────────────────────────────────────────────────────
        const today = new Date()
        const daysAgo = (n: number) => new Date(today.getTime() - n * 86400000).toISOString().split('T')[0]
        const daysAhead = (n: number) => new Date(today.getTime() + n * 86400000).toISOString().split('T')[0]

        const borrowedCopies = copies.filter(c => c.status === 'borrowed')
        const bookCopyForBook = (bookId: string) => borrowedCopies.find(c => c.bookId === bookId)

        // Seed 3 specific borrow records
        const seedBorrowRecords = [
            {
                id: SEED_IDS.borrow1,
                libraryCardId: SEED_IDS.card1,
                bookCopyId: bookCopyForBook(SEED_IDS.book1)?.id ?? copies[1].id,
                librarianId: SEED_IDS.librarianUser,
                borrowDate: daysAgo(10),
                dueDate: daysAhead(4),
                returnDate: null,
                status: 'borrowing',
                renewalCount: 0,
                originalDueDate: null,
                renewedAt: null,
                renewedBy: null,
                createdAt: daysAgo(10) + 'T09:00:00Z',
            },
            {
                id: SEED_IDS.borrow2,
                libraryCardId: SEED_IDS.card1,
                bookCopyId: bookCopyForBook(SEED_IDS.book2)?.id ?? copies[5].id,
                librarianId: SEED_IDS.librarianUser,
                borrowDate: daysAgo(20),
                dueDate: daysAgo(6),
                returnDate: null,
                status: 'overdue',
                renewalCount: 0,
                originalDueDate: null,
                renewedAt: null,
                renewedBy: null,
                createdAt: daysAgo(20) + 'T10:00:00Z',
            },
            {
                id: SEED_IDS.borrow3,
                libraryCardId: SEED_IDS.card1,
                bookCopyId: copies.find(c => c.bookId === SEED_IDS.book3 && c.status === 'available')?.id ?? copies[10].id,
                librarianId: SEED_IDS.librarianUser,
                borrowDate: daysAgo(30),
                dueDate: daysAgo(16),
                returnDate: daysAgo(14),
                status: 'returned',
                renewalCount: 0,
                originalDueDate: null,
                renewedAt: null,
                renewedBy: null,
                createdAt: daysAgo(30) + 'T11:00:00Z',
            },
        ]

        // Auto-generate borrow records for ALL other borrowed copies (not in seed)
        const seedCopyIds = new Set(seedBorrowRecords.filter(r => r.status !== 'returned').map(r => r.bookCopyId))
        const otherBorrowedCopies = borrowedCopies.filter(c => !seedCopyIds.has(c.id))

        for (const copy of otherBorrowedCopies) {
            const borrowDate = daysAgo(7 + Math.floor(Math.random() * 14))
            const dueDate = daysAhead(3 + Math.floor(Math.random() * 10))
            seedBorrowRecords.push({
                id: uuid(),
                libraryCardId: SEED_IDS.card1,
                bookCopyId: copy.id,
                librarianId: SEED_IDS.librarianUser,
                borrowDate,
                dueDate,
                returnDate: null,
                status: 'borrowing',
                renewalCount: 0,
                originalDueDate: null,
                renewedAt: null,
                renewedBy: null,
                createdAt: borrowDate + 'T09:00:00Z',
            })
        }

        this.borrowRecords = seedBorrowRecords

        // ── Reservations ──────────────────────────────────────────────────────────
        this.reservations = [
            {
                id: uuid(),
                libraryCardId: SEED_IDS.card1,
                bookId: SEED_IDS.book2,
                queuePosition: 1,
                status: 'waiting',
                reservedAt: daysAgo(3) + 'T08:00:00Z',
                notifiedAt: null,
                expiresAt: null,
            },
            {
                id: uuid(),
                libraryCardId: SEED_IDS.card1,
                bookId: SEED_IDS.book2,
                queuePosition: 2,
                status: 'waiting',
                reservedAt: daysAgo(2) + 'T09:00:00Z',
                notifiedAt: null,
                expiresAt: null,
            },
            {
                id: uuid(),
                libraryCardId: SEED_IDS.card1,
                bookId: SEED_IDS.book2,
                queuePosition: 3,
                status: 'waiting',
                reservedAt: daysAgo(1) + 'T10:00:00Z',
                notifiedAt: null,
                expiresAt: null,
            },
            {
                id: uuid(),
                libraryCardId: SEED_IDS.card1,
                bookId: SEED_IDS.book6,
                queuePosition: 1,
                status: 'waiting',
                reservedAt: daysAgo(4) + 'T07:00:00Z',
                notifiedAt: null,
                expiresAt: null,
            },
            {
                id: uuid(),
                libraryCardId: SEED_IDS.card1,
                bookId: SEED_IDS.book6,
                queuePosition: 2,
                status: 'waiting',
                reservedAt: daysAgo(3) + 'T11:00:00Z',
                notifiedAt: null,
                expiresAt: null,
            },
            {
                id: uuid(),
                libraryCardId: SEED_IDS.card1,
                bookId: SEED_IDS.book8,
                queuePosition: 1,
                status: 'waiting',
                reservedAt: daysAgo(5) + 'T06:00:00Z',
                notifiedAt: null,
                expiresAt: null,
            },
            {
                id: uuid(),
                libraryCardId: SEED_IDS.card1,
                bookId: SEED_IDS.book20,
                queuePosition: 1,
                status: 'waiting',
                reservedAt: daysAgo(2) + 'T14:00:00Z',
                notifiedAt: null,
                expiresAt: null,
            },
        ]

        // ── Fines ─────────────────────────────────────────────────────────────────
        const overdueDays = 6
        const amount = 5000 + (overdueDays - 5) * 3000
        this.fines = [
            {
                id: uuid(),
                borrowRecordId: SEED_IDS.borrow2,
                fineType: 'overdue',
                overdueDays,
                amount,
                status: 'pending',
                collectedBy: null,
                paymentMethod: null,
                receiptNumber: null,
                paidAt: null,
                createdAt: daysAgo(1) + 'T00:00:00Z',
            },
        ]
    }
}

// Singleton instance
export const db = new MockDB()
